### PR TITLE
Fix all UPLOAD_FILES to be relative to BDUTIL_DIR.

### PR DESCRIPTION
**Pull request by dennishuo**
Fixes hadoop2, querytools, and ambari for running bdutil from a different directory.

### CODE REVIEW

**Comment by dennishuo** [comment]
This was caught in a [StackOverflow thread](http://stackoverflow.com/questions/28238186/hadoop-appendtofile-on-google-compute-engine-cluster/28242101#28242101) by user [Rich](http://stackoverflow.com/users/4100028/rich), thanks Rich!

**Comment by AngusDavis** [comment]
The if [[ -n "BDUTL_DIR" ]] checks seem like they would mask issues until later in the process by not including the uploads if something was screwy with the bdutil invocation.  Does something break without those checks?

Something to consider: Instead of enforcing that all entries in UPLOAD_FILES are absolute paths, have the upload files function resolve path names. The only benefit is decluttering, so I'll leave it up to you.

**Comment by dennishuo** [comment]
Successfully tested querytools/hadoop1 with both Pig and Hive, plain hadoop2, and ambari.

**Comment by dennishuo** [comment]
Yeah, the "if [[ -n BDUTIL_DIR" ]] thing is for consistency for now; mostly it means on the VM-side when hadoop-env-setup.sh is sourced, it doesn't clutter the environment with no-longer-applicable UPLOAD_FILES values. We could add more complex path resolution in a future cl.

**Comment by AngusDavis** [comment]
Acknowledged.
LGTM.

**Pull request merged**
