### PR TITLE
Update Spark configurations to make Cloud Bigtable work with Spark

### PR DESCRIPTION
**Pull request by taragu**
Update Spark configurations to make Cloud Bigtable work with Spark

### CODE REVIEW

**Comment by AngusDavis** [comment]
When running a spark-submit or spark-shell - how do bigtable / hbase jars get onto the classpath (I see ALPN, but I think I'm missing the bigtable specific bits)?

**Comment by taragu** [comment]
Users can specify the Spark classpath using the --jars argument when they run spark-submit or spark-shell. We decided not to append the hbase classpath to spark classpath in spark-default.conf for cases when users don't want to use BigTable.

**Comment by taragu** [comment]
Good idea---I'll add the if check.

**Comment by AngusDavis** [comment]
@sduskis - while I'm cool with that, i can see it either being scary or easy to fat-finger for users. It doesn't need to be in the PR, and I still think the full command should be documented, but consider also providing a wrapper like bigtable-spark-submit and bigtable-spark-shell that can do the hbase classpath and tr magic.

@taragu - LGTM - did tests pass successfully with the change in 9aedd62?

**Comment by taragu** [comment]
@AngusDavis yes, the integration test is continuously running in Jenkins.

**Comment by AngusDavis** [comment]
@taragu - Please rebase / squash commits and I'll merge when you tell me to.

**Comment by taragu** [comment]
@AngusDavis - the commits are squashed. Thank you!

**Pull request merged**
