### PR TITLE
Support for Apache Hama

### PR DESCRIPTION
**Pull request by edwardyoon**
This extension sets up a Apache Hama classic mode cluster atop Hadoop 1 and 2. I would be happy if you merged this because it would make bdutil an even more useful tool.

### CODE REVIEW

**Comment by edwardyoon** [comment]
I signed it!

**Comment by dennishuo** [comment]
Thanks for the pull request! It looks like gs://hama-dist was missing so I went ahead and mirrored the current hama-dist-0.7.0.tar.gz under gs://hama-dist/hama-dist-0.7.0.tar.gz - feel free to contact us at gcp-hadoop-contact@google.com if you want to discuss the options for hosting/referencing the downloadables.

Also, it seems the normal downloadable dist tarball is compiled with Hadoop 2, while bdutil default is currently Hadoop 1; out-of-the-box this will hang on job startup with something like this:

```
java.io.EOFException: End of File Exception between local host is: "dhuo-hama-m.c.hadoop-cloud-dev.google.com.internal/10.240.63.11"; destination host is: "dhuo-hama-m":8020; : java.io.EOFException; For more details see:  http://wiki.apache.org/hadoop/EOFException
  at sun.reflect.GeneratedConstructorAccessor6.newInstance(Unknown Source)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
  at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:792)
  at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:765)
  at org.apache.hadoop.ipc.Client.call(Client.java:1480)
  at org.apache.hadoop.ipc.Client.call(Client.java:1407)
  at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
  at com.sun.proxy.$Proxy9.delete(Unknown Source)
  at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.delete(ClientNamenodeProtocolTranslatorPB.java:540)
  at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
  at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
  at com.sun.proxy.$Proxy10.delete(Unknown Source)
  at org.apache.hadoop.hdfs.DFSClient.delete(DFSClient.java:2049)
  at org.apache.hadoop.hdfs.DistributedFileSystem$14.doCall(DistributedFileSystem.java:707)
  at org.apache.hadoop.hdfs.DistributedFileSystem$14.doCall(DistributedFileSystem.java:703)
  at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
  at org.apache.hadoop.hdfs.DistributedFileSystem.delete(DistributedFileSystem.java:714)
  at org.apache.hama.bsp.BSPMaster.<init>(BSPMaster.java:351)
  at org.apache.hama.bsp.BSPMaster.startMaster(BSPMaster.java:514)
  at org.apache.hama.bsp.BSPMaster.startMaster(BSPMaster.java:500)
  at org.apache.hama.BSPMasterRunner.run(BSPMasterRunner.java:46)
  at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
  at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
  at org.apache.hama.BSPMasterRunner.main(BSPMasterRunner.java:56)
Caused by: java.io.EOFException
  at java.io.DataInputStream.readInt(DataInputStream.java:392)
  at org.apache.hadoop.ipc.Client$Connection.receiveRpcResponse(Client.java:1079)
  at org.apache.hadoop.ipc.Client$Connection.run(Client.java:974)
```

Please either add the following to hama_env.sh:

```
# Default Hama dist tarball requires Hadoop 2.
import_env hadoop2_env.sh
```

Or just specify it in the readme:

```
    ./bdutil -e hadoop2_env.sh -e extensions/hama/hama_env.sh deploy

Or alternatively, using shorthand syntax:

    ./bdutil -e hadoop2 -e hama deploy
```

**Comment by edwardyoon** [comment]
> so I went ahead and mirrored the current hama-dist-0.7.0.tar.gz under gs://hama-dist/hama-dist-0.7.0.tar.gz

Thanks for your help! BTW, the latest release tarball contains hadoop-*.2.7.0 files in lib directory. If there's a version conflict, I will fix install_hama.sh script.

**Comment by dennishuo** [comment]
As discussed in the separate email thread, since we're updating the default Hadoop 2 to 2.7.1 anyways, we can go ahead and just use the default Hama build. Merged manually in https://github.com/GoogleCloudPlatform/bdutil/commit/399a2181332ed9b8c33e8a219968f9a72314c932

Thanks again for the contribution!

**Pull request closed without merging**
